### ISSUE TITLE
Nothing seen on Firefox 62.0 

### ISSUE THREAD

**Issue by erik-larsen** [erik-larsen/emscripten-sdl2-ogles2#14]
None of the samples work on Firefox 62.0.  However they do work on Chrome 69.0 and Safari 10.0.

Steps:
1. https://erik-larsen.github.io/
2. Try any of the samples under emscripten-sdl2-ogles2.

**Comment by erik-larsen** [comment]
Specific to macOS Sierra, not reproducible on High Sierra.

**Comment by tuket** [comment]
I think it's because you need to call `SDL_CreateWindowAndRenderer` intead of `SDL_CreateWindow`. I don't know why, `SDL_CreateWindow` doesn't work for me.

**Comment by erik-larsen** [comment]
Fixed at least since Firefox 108.0.2 👍
